language: node_js
dist: trusty

node_js:
 - "10"

addons:
  chrome: stable

cache: npm

script:
 - ./node_modules/.bin/karma start karma.conf.ts --browsers ChromeHeadlessNoSandbox
 - npm run lint

after_success:
  - bash <(curl -s https://codecov.io/bash)